export const ADD_SEARCH_TAGS = "ADD_SEARCH_TAGS";
export const ADD_SEARCH_TAGS_SUCCESS = "ADD_SEARCH_TAGS_SUCCESS";
export const ADD_SEARCH_TAGS_ERROR = "ADD_SEARCH_TAGS_ERROR";    

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const MAKE_POST = 'MAKE_POST';
export const MAKE_POST_SUCCESS = 'MAKE_POST_SUCCESS';
export const MAKE_POST_ERROR = 'MAKE_POST_ERROR';

export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_ERROR = 'GET_ALL_POSTS_ERROR';

export const GET_POST_BY_ID = "GET_POST_BY_ID"
export const GET_POST_BY_ID_SUCCESS = "GET_POST_BY_ID_SUCCESS"
export const GET_POST_BY_ID_ERROR = "GET_POST_BY_ID_ERROR"

export const MAKE_COMMENT = 'MAKE_COMMENT';
export const MAKE_COMMENT_SUCCESS = 'MAKE_COMMENT_SUCCESS';
export const MAKE_COMMENT_ERROR = 'MAKE_COMMENT_ERROR';

export const GET_COMMENTS_FOR_ONE_POST = 'GET_COMMENTS_FOR_ONE_POST';
export const GET_COMMENTS_FOR_ONE_POST_SUCCESS = 'GET_COMMENTS_FOR_ONE_POST_SUCCESS';
export const GET_COMMENTS_FOR_ONE_POST_ERROR = 'GET_COMMENTS_FOR_ONE_POST_ERROR';

export const MAKE_TAG = 'MAKE_TAG';
export const MAKE_TAG_SUCCESS = 'MAKE_TAG_SUCCESS';
export const MAKE_TAG_ERROR = 'MAKE_TAG_ERROR';

export const GET_TAGS_FOR_ONE_POST = 'GET_TAGS_FOR_ONE_POST';
export const GET_TAGS_FOR_ONE_POST_SUCCESS = 'GET_TAGS_FOR_ONE_POST_SUCCESS';
export const GET_TAGS_FOR_ONE_POST_ERROR = 'GET_TAGS_FOR_ONE_POST_ERROR';

export const CHECK_TAG = 'CHECK_TAG';
export const CHECK_TAG_SUCCESS = 'CHECK_TAG_SUCCESS';
export const CHECK_TAG_ERROR = 'CHECK_TAG_ERROR';

export const SEARCH_POSTS_BY_TAG = 'SEARCH_POSTS_BY_TAG';
export const SEARCH_POSTS_BY_TAG_SUCCESS = 'SEARCH_POSTS_BY_TAG_SUCCESS';
export const SEARCH_POSTS_BY_TAG_ERROR = 'SEARCH_POSTS_BY_TAG_ERROR';

export const CHECK_SOURCE = "CHECK_SOURCE";
export const CHECK_SOURCE_SUCCESS = "CHECK_SOURCE_SUCCESS";
export const CHECK_SOURCE_ERROR = "CHECK_SOURCE_ERROR";

export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR";

export const REMOVE_USER_FROM_TAG = "REMOVE_USER_FROM_TAG";
export const REMOVE_USER_FROM_TAG_SUCCESS = "REMOVE_USER_FROM_TAG_SUCCESS";
export const REMOVE_USER_FROM_TAG_ERROR = "REMOVE_USER_FROM_TAG_ERROR";

export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";

export const EDIT_COMMENT = "EDIT_COMMENT";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const EDIT_COMMENT_ERROR = "EDIT_COMMENT_ERROR";

export const EDIT_POST = "EDIT_POST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_ERROR = "EDIT_POST_ERROR";

export const TURNON_OVERLAY = "TURNON_OVERLAY";
export const TURNOFF_OVERLAY = "TURNOFF_OVERLAY";
export const TOGGLE_OVERLAY = "TOGGLE_OVERLAY";

export const GET_ALL_TAGS = "GET_ALL_TAGS";
export const GET_ALL_TAGS_SUCCESS = "GET_ALL_TAGS_SUCCESS";
export const GET_ALL_TAGS_ERROR = "GET_ALL_TAGS_ERROR";

export const UPDATE_LINK = "UPDATE_LINK";
export const UPDATE_LINK_SUCCESS = "UPDATE_LINK_SUCCESS";
export const UPDATE_LINK_ERROR = "UPDATE_LINK_ERROR";

