version: "3"
services:
    Both:
        container_name: awesome_web
        build: .
        image: vikasraj/awesome_web
        ports:
            - "3000:3000"
        volumes:
            - ./app:/usr/src/app
